### PR TITLE
installed material-ui; installed zustand; installed swiper.js

### PR DESCRIPTION
**Pull request by AdamJablonka**
If more needs to be added, we can discuss later
Installed:
- MUI - component library
- Zustand - global state management
- swiper.js - image carousel library

### CODE REVIEW

**Review by iCarlosVega — APPROVED** [review]
Nice!

**Review by JGangaram — COMMENTED** [review]
Awesome!

**Review by masroor47 — COMMENTED** [review]
Nice, how you doing

**Review by masroor47 — APPROVED** [review]
Now approving

**Review by JGangaram — APPROVED** [review]
Great Work Adam!

**Pull request merged**
